### ISSUE TITLE
make fmriprep doc for beluga

### ISSUE THREAD

**Issue by surchs** [SIMEXP/lab-documentation#10]
We should add documentation for how to run fmriprep on beluga. Good candidate explanations are:
- [x] how to expose and mount the templateflow pre-cached directory (because the compute nodes don't have internet access)
- [ ] how to spawn a slurm task array for a large fmriprep job

**Comment by ltetrel** [comment]
To close:
https://github.com/SIMEXP/lab-documentation/pull/14
