### ISSUE TITLE
[review] python project tutorial

### ISSUE THREAD

**Issue by ltetrel** [SIMEXP/lab-documentation#26]
Hi @FrancoisPgm @MaximilienLC,

We would like to have an external review for this tutorial: https://simexp-documentation.readthedocs.io/en/latest/tutorials/python.html
Do you think you can look at it?

The goal is to help students when starting a python project form zero (including preferable OS, IDE, templates). We don't want to go to far (like python app setup, automatic tests, extensive documentation etc...), this is meant for new python users.

**Comment by htwangtw** [comment]
A warning message was not rendered properly. 
Actually, all my edits were not rendered....
~Need to check the syntax.~
I can render this doc locally... IDK

**Comment by maximilienleclei** [comment]
#27

**Comment by ltetrel** [comment]
> A warning message was not rendered properly. Actually, all my edits were not rendered.... ~Need to check the syntax.~ I can render this doc locally... IDK

To render locally, you can generate the doc with sphynx, let me check the command.

**Comment by htwangtw** [comment]
> > A warning message was not rendered properly. Actually, all my edits were not rendered.... ~Need to check the syntax.~ I can render this doc locally... IDK
> 
> To render locally, you can generate the doc with sphynx, let me check the command.

I mean everything is fine if I render it locally, not sure why the version on the web is not

**Comment by ltetrel** [comment]
@MaximilienLC @FrancoisPgm Let's put this review on hold until we resolve this issue: https://github.com/SIMEXP/lab-documentation/issues/28

**Comment by htwangtw** [comment]
#28 is resolved!

**Comment by ltetrel** [comment]
Great, thx @htwangtw! @MaximilienLC  would you mind checking again with the latest changes ?
@FrancoisPgm any comments ?

**Comment by FrancoisPgm** [comment]
#30 for minor grammar fixes, other than that I don't get what `../compute_canada/project.md` is supposed to refer to. Shouldn't that be a link ? 
Apart from that it looks great to me.

**Comment by maximilienleclei** [comment]
LGTM!

**Comment by ltetrel** [comment]
@FrancoisPgm Yes you are right, I will fix that thx!

**Comment by ltetrel** [comment]
Ok fixed in https://github.com/SIMEXP/lab-documentation/commit/0584d41f4ec99091615606179ed832794e200a65
thank you all for your help,
