### ISSUE TITLE
Latest change to python project tutorial not available on the website

### ISSUE THREAD

**Issue by ltetrel** [SIMEXP/lab-documentation#28]
https://simexp-documentation.readthedocs.io/en/latest/tutorials/python.html doe snot have latest @htwangtw changes.

When rendered locally with: `sphinx-build source/ build/`
The page has latest changes:
![image](https://user-images.githubusercontent.com/37963074/140407391-87c8aa94-5722-4985-b939-64b38bba3a5f.png)

**Comment by htwangtw** [comment]
See: https://github.com/sphinx-doc/sphinx/issues/9788

**Comment by htwangtw** [comment]
Resolved by #29
